In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.shape

(10000, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [9]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [10]:
df.drop(columns=["RowNumber", "Surname", "CustomerId"], inplace=True)

In [11]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
df.shape

(10000, 11)

In [13]:
df = pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True)

In [14]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

## Split Features/target, then train/test split

In [15]:
X = df.drop(columns=["Exited"])
y = df["Exited"].values

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# This standardizes every feature to mean = 0, and std = 1. Feature like "balance"(range from 0 to 250,000) and HasCard(range from 0 to 1) have wildly different scales. Without scaling, the gradient updates for weights attached to large-scale features would dominate the loss landscape, making training unstable or painfully slow.

In [19]:
X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

## Build the Multi layer perceptron

In [22]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [23]:
model = Sequential()

# Hidden layer 1
model.add(Dense(11, activation="sigmoid", input_dim=11))
# Hidden layer 2
model.add(Dense(11, activation="sigmoid"))
# Output layer
model.add(Dense(1, activation="sigmoid"))

# Hidden layer 1, Neurons=11, Input=11 features, Activation=sigmoid
# Hidden layer 2, Neurons=11, Input=11(from hidden 1), Activation=sigmoid
# Output Layer, Neurons=1, Input=11(from hidden 2), Activation=sigmoid

D:\Complete ML\FastAPI\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

## Compile - Defining the loss and optimizer

In [25]:
model.compile(optimizer="Adam", loss="binary_crossentropy", metrics=["accuracy"])

# loss is BCE, used because this is binary classification
# Optimizer = "adam" --> A smarter version of gradient descent.
# accuracy --> just for human-readable monitoring, not used in the actual weight updates

## Train - Forward prop + backprop + gradient descent, looped

In [26]:
history = model.fit(X_train, y_train, batch_size=50, epochs=100, verbose=1, validation_split=0.2)

# This single line is the entire training loop you've been deriving by hand, automated:

Epoch 1/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2066 - loss: 1.0782 - val_accuracy: 0.2013 - val_loss: 0.7749
Epoch 2/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6439 - loss: 0.6486 - val_accuracy: 0.7987 - val_loss: 0.5663
Epoch 3/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5386 - val_accuracy: 0.7987 - val_loss: 0.5144
Epoch 4/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5128 - val_accuracy: 0.7987 - val_loss: 0.5021
Epoch 5/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5068 - val_accuracy: 0.7987 - val_loss: 0.4989
Epoch 6/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5058 - val_accuracy: 0.7987 - val_loss: 0.4982
Epoch 7/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5054 - val_accuracy: 0.7987 - val_loss: 0.4978
Epoch 8/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5052 - val_accuracy: 0.7987 - val_loss: 0.4975
Epoch 9/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5051 - val_accuracy: 0.7987 - val_loss: 0.4973
Epoch 10/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5048 - val_accuracy: 0.7987 - val_loss: 0.4970
Epoch 11/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5046 - val_accuracy: 0.7987 - val_loss: 0.4967
Epoch 12/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5044 - val_accuracy: 0.7987 - val_loss: 0.4966
Epoch 13/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5045 - val_accuracy: 0.7987 - val_loss: 0.4966
Epoch 14/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5044 - val_accuracy: 0.7987 - val_loss: 0.4963
Epoch 15/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5043 - val_accuracy: 0.7987 - val_loss: 0.4960
Epoch 16/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5040 - val_accuracy: 0.7987 - val_loss: 0.4959
Epoch 17/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5044 - val_accuracy: 0.7987 - val_loss: 0.4959
Epoch 18/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5041 - val_accuracy: 0.7987 - val_loss: 0.4955
Epoch 19/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5040 - val_accuracy: 0.7987 - val_loss: 0.4950
Epoch 20/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5037 - val_accuracy: 0.7987 - val_loss: 0.4948
Epoch 21/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5035 - val_accuracy: 0.7987 - val_loss: 0.4947
Epoch 22/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5035 - val_accuracy: 0.7987 - val_loss: 0.4944
Epoch 23/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5033 - val_accuracy: 0.7987 - val_loss: 0.4942
Epoch 24/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5031 - val_accuracy: 0.7987 - val_loss: 0.4941
Epoch 25/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5031 - val_accuracy: 0.7987 - val_loss: 0.4939
Epoch 26/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4941
Epoch 27/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5030 - val_accuracy: 0.7987 - val_loss: 0.4938
Epoch 28/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4937
Epoch 29/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5030 - val_accuracy: 0.7987 - val_loss: 0.4940
Epoch 30/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4935
Epoch 31/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4935
Epoch 32/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5030 - val_accuracy: 0.7987 - val_loss: 0.4935
Epoch 33/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4935
Epoch 34/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4937
Epoch 35/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 36/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5030 - val_accuracy: 0.7987 - val_loss: 0.4933
Epoch 37/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4933
Epoch 38/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 39/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4932
Epoch 40/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4934
Epoch 41/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4933
Epoch 42/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4934
Epoch 43/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4934
Epoch 44/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4932
Epoch 45/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 46/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 47/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4932
Epoch 48/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4933
Epoch 49/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 50/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 51/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 52/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 53/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4927
Epoch 54/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 55/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5034 - val_accuracy: 0.7987 - val_loss: 0.4941
Epoch 56/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5036 - val_accuracy: 0.7987 - val_loss: 0.4942
Epoch 57/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5035 - val_accuracy: 0.7987 - val_loss: 0.4937
Epoch 58/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5033 - val_accuracy: 0.7987 - val_loss: 0.4940
Epoch 59/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5033 - val_accuracy: 0.7987 - val_loss: 0.4933
Epoch 60/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5030 - val_accuracy: 0.7987 - val_loss: 0.4934
Epoch 61/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4935
Epoch 62/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4932
Epoch 63/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4933
Epoch 64/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 65/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4929
Epoch 66/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5030 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 67/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 68/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 69/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 70/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4928
Epoch 71/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4926
Epoch 72/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4926
Epoch 73/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5028 - val_accuracy: 0.7987 - val_loss: 0.4926
Epoch 74/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4925
Epoch 75/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4924
Epoch 76/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4926
Epoch 77/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4926
Epoch 78/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4923
Epoch 79/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4927
Epoch 80/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4925
Epoch 81/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4924
Epoch 82/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 83/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 84/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4925
Epoch 85/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 86/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4925
Epoch 87/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 88/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 89/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 90/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 91/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 92/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 93/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 94/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 95/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 96/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 97/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 98/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5025 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 99/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 100/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4919

In [27]:
model.layers[0].get_weights()

[array([[-0.2601787 , -0.31957692,  0.4364404 ,  0.23422603,  0.00084092,
         -0.08477104,  0.3732881 , -0.37651837, -0.44407076, -0.31806093,
          0.1285244 ],
        [ 0.381344  , -0.1890641 ,  0.5930985 , -0.4386287 ,  0.36552212,
         -0.34451675, -0.5036457 ,  0.23868369,  0.5150391 , -0.08821724,
          0.25847203],
        [-0.13570382,  0.1457816 ,  0.2775268 ,  0.46336028,  0.28454313,
         -0.49570063, -0.06192744,  0.35725614, -0.42361882, -0.29071018,
         -0.49579528],
        [-0.37977013, -0.21330029,  0.0074457 ,  0.23026848, -0.36165273,
         -0.261434  ,  0.28291792,  0.44485044,  0.15374903,  0.5132094 ,
         -0.05154423],
        [ 0.24573757,  0.25578973,  0.5337685 ,  0.21345541, -0.4592104 ,
          0.42799303, -0.08576089, -0.17968084,  0.48706725,  0.06359377,
          0.2826049 ],
        [ 0.13085288, -0.44121945,  0.5975632 , -0.294116  , -0.02814925,
          0.5014573 , -0.28035426,  0.28747383,  0.52047694, -0.21249707,
         -0.3585048 ],
        [-0.0260807 ,  0.31733024,  0.4537541 ,  0.49217352, -0.31190875,
         -0.3071986 ,  0.40031308, -0.5041496 ,  0.25124198,  0.6945818 ,
          0.12650697],
        [ 0.24198624,  0.332337  ,  0.27382508, -0.42317522,  0.06299295,
          0.40500006,  0.10705525, -0.00514592, -0.41476917,  0.3323944 ,
          0.35428187],
        [-0.3211116 ,  0.06180923, -0.04332444, -0.33592236,  0.2217204 ,
          0.30077687,  0.5133912 , -0.18709216, -0.3476967 , -0.2229884 ,
          0.50377065],
        [-0.28449684,  0.2790637 ,  0.1366603 , -0.12058747, -0.49079353,
         -0.44125563,  0.35391343, -0.1903485 ,  0.4309694 ,  0.3195049 ,
          0.12337425],
        [ 0.20961586, -0.3509034 ,  0.44042912, -0.5189302 , -0.32024366,
          0.25606826,  0.07103807, -0.05927072,  0.01630121, -0.01368589,
          0.47481462]], dtype=float32),
 array([ 0.0736615 ,  0.02534576,  0.10320474, -0.00497853,  0.00035985,
        -0.02166148,  0.        , -0.00842327,  0.01097392,  0.02870682,
         0.02750088], dtype=float32)]

In [28]:
model.layers[1].get_weights()

[array([[-2.82369345e-01,  3.76728438e-02, -2.39534542e-01,
          1.83606312e-01, -1.72302574e-02, -7.33739436e-01,
         -3.86857808e-01,  5.31021953e-01, -1.97490126e-01,
         -1.79377481e-01,  5.41225970e-01],
        [ 1.20983243e-01, -3.35750312e-01, -2.23344415e-01,
          1.29568264e-01,  1.39981285e-01,  8.04289654e-02,
          3.05331796e-01,  4.35649663e-01, -4.83080178e-01,
          2.49525666e-01, -4.28132750e-02],
        [-5.28728187e-01,  6.74832523e-01, -3.24587375e-01,
          9.09416229e-02, -5.63261449e-01,  1.12181515e-01,
          2.21807972e-01, -2.02054307e-01, -5.18211186e-01,
          1.15934186e-01, -5.36780357e-01],
        [ 8.37742910e-02, -2.47292861e-01, -3.14284831e-01,
         -4.24376540e-02, -3.77198756e-01, -4.68546897e-01,
          3.28044146e-01,  1.61793664e-01, -3.42267871e-01,
          3.11786115e-01,  3.43086004e-01],
        [-9.39508617e-01,  6.16998494e-01,  5.21116257e-02,
         -1.19726050e+00, -4.07873005e-01, -5.70006371e-01,
         -7.87092030e-01,  7.32488692e-01, -3.14036787e-01,
          1.15175867e+00, -9.76994276e-01],
        [ 4.84335363e-01,  5.15694469e-02, -4.85747792e-02,
         -1.04415141e-01, -2.28553995e-01, -1.40959397e-01,
          1.30862653e-01, -2.44873926e-01, -3.08726907e-01,
         -5.91410848e-04,  2.39371851e-01],
        [-6.60925090e-01,  7.22982347e-01,  1.41450211e-01,
         -1.04872733e-01, -5.07567644e-01, -7.42157936e-01,
         -3.23907226e-01,  3.82541567e-01, -1.05947711e-01,
         -1.47664085e-01, -4.60211694e-01],
        [-1.00443125e-01, -4.24203902e-01, -1.69332907e-01,
         -4.06333476e-01,  4.05898057e-02, -1.81484997e-01,
          5.16712248e-01,  1.72028646e-01,  1.65530533e-01,
         -3.75004381e-01,  1.33664027e-01],
        [ 5.05659461e-01,  4.53880906e-01, -4.64726865e-01,
          3.36242169e-01,  3.19318444e-01, -4.77213040e-02,
          3.79264414e-01,  5.31867743e-01, -2.56552279e-01,
         -7.49711841e-02,  6.94558918e-02],
        [ 1.49246901e-01,  4.15418595e-01, -6.44004405e-01,
         -2.56881624e-01, -5.54110436e-03,  2.11745471e-01,
          1.37758553e-01,  1.55153364e-01, -5.32271564e-02,
          2.51643956e-01, -4.00018930e-01],
        [ 1.58948228e-01, -1.62514046e-01, -1.09293096e-01,
          2.14997679e-03, -8.40687454e-02, -2.50186235e-01,
         -2.87361830e-01,  4.92228180e-01, -1.10708168e-02,
          6.12541996e-02, -1.24788217e-01]], dtype=float32),
 array([-0.17290024,  0.3373525 , -0.17863552, -0.28036037, -0.33479452,
        -0.275811  , -0.17400129,  0.3768383 , -0.34442115,  0.2438838 ,
        -0.18421526], dtype=float32)]

In [29]:
model.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step

array([[0.20977397],
       [0.21257545],
       [0.22862145],
       ...,
       [0.1978731 ],
       [0.21101052],
       [0.19484703]], shape=(2000, 1), dtype=float32)

In [30]:
y_log = model.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step

In [31]:
y_pred = np.where(y_log >0.5, 1, 0)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8035